AWSTemplateFormatVersion: "2010-09-09"
Description: "s3-parametrized bucket with versioning enabled"
Parameters:
  BucketName:
    Description: "Name of the bucket"
    Type: String
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled