version: 0.2
env:
  parameter-store:
    DOCKER_REGISTRY_USER: "DOCKER_REGISTRY_USER"
    DOCKER_REGISTRY_PASSWORD: "DOCKER_REGISTRY_PASSWORD"

phases:
  install:
    runtime_versions:
      python:3.11
  pre_build:
    commands:
      - pip install -r codepipeline/requirements.txt
  build:
    commands:
      - echo "---------------------------------------------------------------------------------------------------"
      - cd codepipeline
      - echo "Building python based docker image"
      - docker build -t $DOCKER_REGISTRY_USER/py-app:latest .
      - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin
      - docker push "docker.io/$DOCKER_REGISTRY_USER/py-app:latest"
  post_build:
    commands:
      - echo "---------------------------------------------------------------------------------------------------"
      - echo "Build is completed"
  
